### PR TITLE
Add instructions for using the checker and a sample application

### PR DESCRIPTION
**Pull request by bennostein**
@lazaroclapp As discussed via email, here are some instructions to configure an application with the RxThreadEffectChecker, as well as a basic sample application configured according to the instructions.  Specifying jars as gradle dependencies seems a little sketchy, but was the simplest way I could think of to use the checker.  Perhaps it would be worthwhile in the future to get the checker published in Maven, but that's a conversation for another time.

### CODE REVIEW

**Review by lazaroclapp — APPROVED** [review]
LGTM.

**Comment by msridhar** [comment]
We should definitely throw up a jar on Maven Central.  See #3.

@bennostein I'm wondering how Travis still passes with this PR.  Do we not actually run the Rx checker on the sample app in the Travis build?  Seems like if we did it should fail with an error.

**Comment by bennostein** [comment]
Yes, I didn't make any changes to the Travis script with this PR.  Should I? My thinking was that the sample app isn't part of the checker and shouldn't be part of CI, but happy to un-break the sample app and add its build to Travis if you'd like.

**Comment by msridhar** [comment]
The nice thing about building the sample app on CI is that it ensures our config is copy-paste-able for someone who wants to use the tool.  But, I'm ok with doing that in a follow up; from my experience it's a bit painful to get the config in place to get Android apps building on Travis (though copy-pasting from NullAway should make things easier).

**Comment by msridhar** [comment]
Thanks @bennostein!

**Pull request merged**
